version: '3'
services:
   ubuntu:
      build: .
      privileged: true
      image: ubuntu2004
      container_name: ubuntu2004
      tty: true
      volumes:
         - ./src:/home/saitenntaisei/src
      extra_hosts:
         - host.docker.internal:host-gateway
